# Athit Vue
# Chris White
# CSCI 446
# Spring 2016
# Makefile for Program 2: t-counter
CXX = gcc
CXXFLAGS = -g -Wall -W -Werror -pedantic
all:	t-counter
t-counter: t-counter.c
	$(CXX) $(CXXFLAGS) -o t-counter t-counter.c
clean:
	rm -f *.o t-counter
