#####################################
## Name: Athit Vue and Chris White ##
## Class: CSCI 446                 ##
## Semester: Fall 2016             ##
## Date: 09/19/2016                ##
#####################################

########MAKEFILE STARTS####################

convert4to5: convert4to5.cpp
	g++ -g -std=c++11 -Wall -W -Werror -pedantic -o convert4to5 convert4to5.cpp
clean:
	rm -f convert4to5 convert4to5.exe convert4to5.o
########MAKEFILE ENDS#####################
