# Athit Vue
# Chris White
# CSCI 446
# Spring 2016
# Makefile for Program 2: t-counter
CXX = gcc
CXXFLAGS = -g -Wall -W -Werror -pedantic
all:	server
server: server.c
	$(CXX) $(CXXFLAGS) -o server server.c
clean:
	rm -f *.o server
